### ISSUE TITLE
"Disco mode" on IE10

### ISSUE THREAD

**Issue by thomaslanciaux** [nemeseri/ender-overlay#2]
Hello, 
Just noticed a bug on IE10 : the overlay is looping in the "open" function, you won't be able to close the pop-in anymore then. This happens also on the demo page : 
http://nemeseri.com/ender-overlay/demos/content-types.html

**Comment by turtledove999** [comment]
I'm also seeing this in Chrome Canary (v 25.0.1336.0, Mac OS X 10.8.2), for what it's worth.

**Comment by nemeseri** [comment]
I just fixed this issue in the latest version. It was solved by updating Jeesh.

**Comment by thomaslanciaux** [comment]
many thanks Andras 

Thomas

**Comment by symmetriq** [comment]
This is now happening in the current WebKit nightly (r152204) as well. My copy of Jeesh is up-to-date (all Ender modules are).

This is my ender info output:

Active packages:
└─┬ ender-overlay@0.2.5 - Highly customizable overlay for Ender
  ├── morpheus@0.6.7 - A Brilliant Animator
  └─┬ jeesh@0.0.6 - The official starter pack for Ender.
    ├── bean@1.0.4 - A small, fast, framework-agnostic event manager
    ├── bonzo@1.3.5 - Library agnostic, extensible DOM utility
    ├── domready@0.2.11 - bullet proof DOM ready method
    └── qwery@3.4.1 - blazing fast CSS3 query selector engine

**Comment by symmetriq** [comment]
Still happening in the current WebKit build, and now I'm seeing this in Safari on iOS 7 as well.

Disabling animation (setting both animationIn and animationOut to "none") fixes it for me, so at least there's a workaround for now. Maybe the issue is actually in Morpheus?

Only problem is: disabling animation causes a different issue in IE. My overlay will appear the first time, but after that, only the mask appears (overlay does not show up at all). So I need animation _enabled_ for IE, and disabled for WebKit. Strange.
